spring.application.name=Spring04

# Spring Boot 설정 파일
# Tomcat Server Port 설정
server.port=8081

# Context Path
# localhost:8081/controller/boardList.do
server.servlet.context-path=/

# DB Connection 정보 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://project-db-campus.smhrd.com:3312/sc_26K_HI2_p2_1
spring.datasource.username=sc_26K_HI2_p2_1
spring.datasource.password=smhrd1

# JPA 설정
# MYSQL 사용 설정
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 스키마 설정 (create, update)
spring.jpa.hibernate.ddl-auto=update

# hibernate가 만든 sql문장 볼 수 있게 설정
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 뷰리졸버 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Web Push
vapid.public-key=BH5GKGd8KdR1Ks80OHZEJHFV49Xoj4DQpmRNcpAnIYuJme0UyMCcJfQz57HuhYNIsqUjyAmYB2vZ2BglsIAH0MU
vapid.private-key=private-key
vapid.subject=mailto:1234@example.com
